# ce docker compose va contenir ces differents composants 
#Prometheus, grafana, alertmanager
#jenkins exporter 1,2,3, exporter mongo, exporter apache
#

version: '2.1'

volumes:
    prometheus_data: {}
    grafana_data: {}


services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9999:9090"



  grafana:
    image: grafana/grafana 
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
     - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
     - GF_PATHS_DATA=/var/lib/grafana
     - GF_PATHS_HOME=/usr/share/grafana
     - GF_PATHS_LOGS=/var/log/grafana
     - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/app/list/data/grafana

    #restart: always

